/**
 * Central export for all shared types
 */

// Settings types
export type {
  ChannelId,
  VideoId,
  WhitelistId,
  CustomDomainId,
  ShortVideoPlatform,
  FullSitePlatform,
  SNSPlatform,
  Platform,
  ShortVideoPlatformSettings,
  FullSitePlatformSettings,
  SNSPlatformSettings,
  PlatformSettings,
  WhitelistType,
  WhitelistEntry,
  CustomBlockedDomain,
  DayOfWeek,
  TimeRange,
  ScheduleConfig,
  BlockPageTheme,
  BlockPageSettings,
  FocusDuration,
  FocusModeSettings,
  FocusModeState,
  PomodoroMode,
  PomodoroSettings,
  PomodoroState,
  SiteTimeLimit,
  SiteTimeUsage,
  TimeLimitsSettings,
  TimeLimitsState,
  DailyTimeRecord,
  TimeTrackingSettings,
  TimeTrackingState,
  StreakSettings,
  StreakData,
  ChallengeDifficulty,
  ChallengeType,
  ChallengeSettings,
  ChallengeData,
  ChallengeState,
  LockdownSettings,
  LockdownState,
  BlockingStats,
  UserPreferences,
  PopupView,
  Settings,
  SettingsUpdate,
} from './settings';

export {
  isValidSettings,
  isValidWhitelistEntry,
  isValidCustomBlockedDomain,
} from './settings';

// Rules types
export type {
  DetectionMethod,
  BlockingAction,
  UrlRule,
  SelectorRule,
  AttributeRule,
  BlockingRule,
  PlatformRules,
  CustomRule,
} from './rules';

export { isValidBlockingRule } from './rules';

// Log types
export type { LogLevel, AppLogEntry } from './logs';

// Message types
export type {
  MessageType,
  Message,
  GetSettingsMessage,
  UpdateSettingsMessage,
  GetStatsMessage,
  LogBlockMessage,
  WhitelistAddMessage,
  WhitelistRemoveMessage,
  PingMessage,
  FocusStartMessage,
  FocusCancelMessage,
  FocusGetStateMessage,
  FocusExtendMessage,
  PomodoroStartMessage,
  PomodoroPauseMessage,
  PomodoroResumeMessage,
  PomodoroStopMessage,
  PomodoroSkipMessage,
  PomodoroGetStateMessage,
  TimeTrackActivityMessage,
  TimeGetUsageMessage,
  TimeResetUsageMessage,
  TimeCheckLimitMessage,
  TimeGetHistoryMessage,
  TimeClearHistoryMessage,
  StreakGetDataMessage,
  StreakResetMessage,
  StreakCheckDayMessage,
  ChallengeRequestMessage,
  ChallengeSubmitMessage,
  ChallengeGetStateMessage,
  LockdownSetPinMessage,
  LockdownVerifyPinMessage,
  LockdownActivateMessage,
  LockdownDeactivateMessage,
  LockdownGetStateMessage,
  LockdownRequestEmergencyBypassMessage,
  LockdownCheckEmergencyBypassMessage,
  MessageResponse,
  GetSettingsResponse,
  UpdateSettingsResponse,
  GetStatsResponse,
  LogBlockResponse,
  WhitelistAddResponse,
  WhitelistRemoveResponse,
  PingResponse,
  FocusStartResponse,
  FocusCancelResponse,
  FocusGetStateResponse,
  FocusExtendResponse,
  PomodoroStartResponse,
  PomodoroPauseResponse,
  PomodoroResumeResponse,
  PomodoroStopResponse,
  PomodoroSkipResponse,
  PomodoroGetStateResponse,
  TimeTrackActivityResponse,
  TimeGetUsageResponse,
  TimeResetUsageResponse,
  TimeCheckLimitResult,
  TimeCheckLimitResponse,
  TimeGetHistoryResponse,
  TimeClearHistoryResponse,
  StreakGetDataResponse,
  StreakResetResponse,
  StreakCheckDayResponse,
  ChallengeSubmitResult,
  ChallengeRequestResponse,
  ChallengeSubmitResponse,
  ChallengeGetStateResponse,
  LockdownVerifyPinResult,
  EmergencyBypassCheckResult,
  LockdownSetPinResponse,
  LockdownVerifyPinResponse,
  LockdownActivateResponse,
  LockdownDeactivateResponse,
  LockdownGetStateResponse,
  LockdownRequestEmergencyBypassResponse,
  LockdownCheckEmergencyBypassResponse,
} from './messages';

export {
  MESSAGE_TYPES,
  isValidMessage,
  isMessageType,
  createMessage,
} from './messages';
